version: '3.7'

services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    hostname: cloudflare-ddns.local
    image: docker.io/timothyjmiller/cloudflare-ddns@sha256:f6f6d05ca31975a616613402ba2d86db76a91ec65fab82be2036cf407b43634e
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./config/config.json:/config.json:ro
    network_mode: "host"