version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.11-alpine
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    environment:
      - TZ=Europe/Copenhagen
    dns:
      - 10.8.1.3
    networks:
      wgeasy-pihole-unbound_wgeasy:
        ipv4_address: 10.8.1.4

networks:
  wgeasy-pihole-unbound_wgeasy:
    external: true