version: "3.3"

services:
  uptimekuma:
    container_name: uptimekuma
    hostname: uptimekuma.local
    image: louislam/uptime-kuma:1.23.13-debian
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./data:/app/data:rw
    networks:
      - wgeasy-pihole-unbound_wgeasy
    ports:
      - 3001:3001
    dns:
      - 10.8.1.3

networks:
  wgeasy-pihole-unbound_wgeasy:
    external: true