version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden.local
    image: docker.io/vaultwarden/server:1.30.5-alpine
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
        LOGIN_RATELIMIT_MAX_BURST: 10
        LOGIN_RATELIMIT_SECONDS: 60
        DOMAIN: "https://vaultwarden.wraaath.com"
        INVITATIONS_ALLOWED: "true"
        ADMIN_TOKEN: ${ADMIN_TOKEN}
        EMERGENCY_ACCESS_ALLOWED: "true"
        SENDS_ALLOWED: "true"
        WEB_VAULT_ENABLED: "true"
    volumes:
      - ./data/:/data/:rw
    networks:
      - proxy
    ports:
      - 8062:80
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.vaultwarden-https.rule=Host(`vaultwarden.wraaath.com`)
        - traefik.http.routers.vaultwarden-https.entrypoints=https
        - traefik.http.routers.vaultwarden-https.tls=true
        - traefik.http.routers.vaultwarden-https.service=vaultwarden
        - traefik.http.routers.vaultwarden-http.rule=Host(`vaultwarden.wraaath.com`)
        - traefik.http.routers.vaultwarden-http.entrypoints=http
        - traefik.http.routers.vaultwarden-http.middlewares=redirect-https
        - traefik.http.routers.vaultwarden-http.service=vaultwarden
        - traefik.http.services.vaultwarden.loadbalancer.server.port=80

networks:
  proxy:
    external: true
