version: "3.3"
services:
  jellyfin-bot:
    ports:
      - "3005:3005"
    environment:
      - DISCORD_CLIENT_TOKEN=${discord_client_token}
      - JELLYFIN_SERVER_ADDRESS=${jellyfin_server_address}
      - JELLYFIN_AUTHENTICATION_USERNAME=${jellyfin_auth_user}
      - JELLYFIN_AUTHENTICATION_PASSWORD=${jellyfin_auth_pass}
    image: "ghcr.io/manuel-rw/jellyfin-discord-music-bot:test-max-item-length"