version: "3.3"

services:
  jellyfin-bot:
    container_name: jellyfin-bot
    hostname: jellyfin-bot.local
    image: ghcr.io/manuel-rw/jellyfin-discord-music-bot@sha256:3db40815a3b67f945f670acd53072ce3f3efca1b86bfb00bffa090bb5ff3abcd
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
        DISCORD_CLIENT_TOKEN: ${discord_client_token}
        JELLYFIN_SERVER_ADDRESS: ${jellyfin_server_address}
        JELLYFIN_AUTHENTICATION_USERNAME: ${jellyfin_auth_user}
        JELLYFIN_AUTHENTICATION_PASSWORD: ${jellyfin_auth_pass}
    networks:
      - proxy
    ports:
      - 3005:3005

networks:
  proxy:
    external: true