version: "2.1"

services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant.local
    image: lscr.io/linuxserver/homeassistant:2024.5.5
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
        TZ: Europe/Copenhagen
        PUID: 1000
        PGID: 1000
    volumes:
      - ./config:/config:rw
    networks:
      - proxy
    ports:
      - 8123:8123

networks:
  proxy:
    external: true