version: "3"
networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: mvance/unbound:1.19.0
    container_name: unbound
    restart: unless-stopped
    hostname: unbound
    volumes:
      - ./config/unbound/:/opt/unbound/etc/unbound/
    networks:
      private_network:
        ipv4_address: 10.2.0.200
    cap_add:
      - NET_ADMIN
    env_file: .env

  wireguard:
    depends_on:
      - unbound
      - pihole
    image: linuxserver/wireguard@sha256:28636a8aae70b379965eb12da8203b1829d4bd39a6495632befbea1dc3073c5a
    container_name: wireguard
    ports:
      - 5000:5000
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    volumes:
      - ./config/wireguard/:/config
    env_file: .env

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:0.6.2
    container_name: wireguard-ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./config/wireguard-ui/db/:/app/db
      - ./config/wireguard-ui/:/config
    env_file: .env

  pihole:
    depends_on:
      - unbound
    container_name: pihole
    image: pihole/pihole:2024.01.0
    restart: unless-stopped
    hostname: pihole
    dns:
      - 127.0.0.1
      - ${PIHOLE_DNS}
    volumes:
      - ./config/pihole/etc-pihole/:/etc/pihole/
      - ./config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    networks:
      private_network:
        ipv4_address: 10.2.0.100
    env_file: ./.env