version: "3.7"

services:
  <service_name>:
    container_name: <container_name>
    hostname: <hostname>
    image: <platform/user/image:tag>
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ: Europe/Copenhagen
      - PUID: 1000
      - PGID: 1000
      - <environment_variable>: <value>
      - <environment_variable2>: ${ENV_VAR}
    volumes:
      - ./data/<service>:/<container_path>:rw
      - ./config/<service>:/<container_path>:ro
    networks:
      - proxy
    ports:
      - 69:69/tcp
      - 6969:6969/udp

networks:
  proxy:
    external: true