version: "3.7"

services:
  wgeasy:
    environment:
      # ⚠️ Change the server's hostname (clients will connect to):
      - WG_HOST=${PUBLIC_IP}

      # ⚠️ Change the Web UI Password:
      - PASSWORD=${WGEASY_PASS}

      # 💡 This is the Pi-Hole Container's IP Address
      - WG_DEFAULT_DNS=10.8.1.3
      - WG_DEFAULT_ADDRESS=10.8.0.x
    image: ghcr.io/wg-easy/wg-easy:10
    container_name: wg-easy
    volumes:
      - ./config/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      wgeasy:
        ipv4_address: 10.8.1.2

  pihole-unbound:
    container_name: pihole-unbound
    image: rlabinc/pihole-unbound@sha256:6bada19677a01ddc3ba4015c9393455f211690da454e9962a01446eeee32f7fa
    hostname: pihole
    domainname: pihole.local
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335/tcp # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=Europe/Copenhagen
      - WEBPASSWORD=${PIHOLE_PASS}
      - WEBTHEME=default-dark
      - REV_SERVER=true
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
    volumes:
      - ./config/pihole/etc_pihole-unbound:/etc/pihole:rw
      - ./config/pihole/etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
    networks:
      wgeasy:
        ipv4_address: 10.8.1.3

networks:
  wgeasy:
    ipam:
      config:
        - subnet: 10.8.1.0/24