version: "3.7"

services:
  vscodium:
    container_name: vscodium
    hostname: vscodium.local
    image: lscr.io/linuxserver/vscodium:1.87.0
    env_file: .env
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      TZ: Europe/Copenhagen
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"