version: '3.9'
services:
  apache:
    image: httpd:alpine3.18@sha256:ecf19d91df773a43b1df424b77dfe42e992129de74919ce40f764f57e1f1fe85
    restart: unless-stopped
    container_name: website
    networks:
    - proxy
    ports:
    - '8080:80'
    volumes:
    - ./data:/usr/local/apache2/htdocs
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.website-https.rule=Host(`wraaath.com`)
        - traefik.http.routers.website-https.entrypoints=https
        - traefik.http.routers.website-https.tls=true
        - traefik.http.routers.website-https.service=website
        - traefik.http.routers.website-http.rule=Host(`wraaath.com`)
        - traefik.http.routers.website-http.entrypoints=http
        - traefik.http.routers.website-http.middlewares=redirect-https
        - traefik.http.routers.website-http.service=website
        - traefik.http.services.website.loadbalancer.server.port=80
    
networks:
  proxy:
    external: true