version: "3.9"

services:
  papermc-server:
    container_name: papermc-server
    hostname: papermc-server.local
    image: docker.io/marctv/minecraft-papermc-server@sha256:c57a2384aeaaf75f44bbdac156c7750e496f21aa085ef0ca77322ce7c4b9c7d2
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Copenhagen
      PUID: 1000
      PGID: 1000
      MEMORYSIZE: "12G"
      PAPERMC_FLAGS: ""
    networks:
      - proxy
    volumes:
      - ./data:/data:rw
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true

networks:
  proxy:
    external: true