version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server@sha256:50d7c98ca44e238924650d4281ed347391674bcb905d35cdfdc8a2d1bf8c2341"
    restart: always
    container_name: "papermc-server"
    environment:
      MEMORYSIZE: "12G"
      PAPERMC_FLAGS: ""
      TZ: Europe/Copenhagen
    volumes:
      - "./data:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true