version: "3.9"
services:
  minecraft:
    image: "marctv/minecraft-papermc-server@sha256:f74cff4b6fb6a7cc0e2d82977486eb7210e765b506a96a93893a474a38127e1a"
    restart: always
    container_name: "papermc-server"
    environment:
      MEMORYSIZE: "12G"
      PAPERMC_FLAGS: ""
      TZ: Europe/Copenhagen
    volumes:
      - "./data:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true