version: '3.7'

services:
  searxng:
    image: searxng/searxng:2023.7.1-5720844f
    container_name: searxng
    restart: unless-stopped
    volumes:
      - ./config:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - TZ=Europe/Copenhagen
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    ports:
      - 8880:8080
    networks:
      - proxy
    labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
        - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
        - traefik.http.routers.searxng-https.rule=Host(`searxng.wraaath.com`)
        - traefik.http.routers.searxng-https.entrypoints=https
        - traefik.http.routers.searxng-https.tls=true
        - traefik.http.routers.searxng-https.service=searxng
        - traefik.http.routers.searxng-http.rule=Host(`searxng.wraaath.com`)
        - traefik.http.routers.searxng-http.entrypoints=http
        - traefik.http.routers.searxng-http.middlewares=redirect-https
        - traefik.http.routers.searxng-http.service=searxng
        - traefik.http.services.searxng.loadbalancer.server.port=80

networks:
  proxy:
    external: true